### PR TITLE
Update combatinitation.lua

### PR DESCRIPTION
**Pull request by cryptalmist**
now can enable even equiped

can you change to toggles instead of buttons?

tripmine not work i think the other too

### CODE REVIEW

**Comment by cryptalmist** [comment]
and saving the selection

**Comment by marik611377** [comment]
thx for the update :D
your commit is appericated

**Comment by marik611377** [comment]
i'll work on changing buttons to toggles instead

**Comment by marik611377** [comment]
by the way, _**saving the selection**_ idk how to

**Comment by cryptalmist** [comment]
> by the way, _**saving the selection**_ idk how to

load/save config? :)
and auto load on startup
create a configfolder too dont use the test folder

**Pull request merged**
